### ISSUE TITLE
Address PMC requirements

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/grizzly-memcached#1]
All EE4J projects must follow PMC requirements described here:
https://www.eclipse.org/ee4j/news/?date=2018-02-16

**Comment by m0mus** [comment]
Any progress?

**Comment by carryel** [comment]
@m0mus Unfortunately, the project is not related to Java EE but is derived from https://github.com/eclipse-ee4j/grizzly.
So I have questions.
- Is it obligatory to follow PMC requirements in spite of this situation? 
- Could there be an exceptional project?

**Comment by m0mus** [comment]
If this project is not a part of Jakarta EE platform (GlassFish) it's not required and you can close this task.

**Comment by m0mus** [comment]
Yes, I see, the URL is changed because of the web site redesign. I found it here: https://www.eclipse.org/ee4j/news/?date=2018-02-16

@waynebeaton can we have a proper permalink for this document?
