### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/grizzly-memcached#2]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)
- [Release job on the new cloud infra](https://wiki.eclipse.org/JakartaEE_New_Infra_Release_Job)

**Comment by m0mus** [comment]
According to Jignesh, it's not needed for GF 5.1 release. Removing it from the project board.

**Comment by anajosep** [comment]
The release jobs are configured for this project at 
https://ci.eclipse.org/grizzly/job/Grizzly-Memcached-master_release/

The artifacts are available in the OSSRH Staging repository as well as released to Maven central repository at the below location:
http://central.maven.org/maven2/org/glassfish/grizzly/grizzly-memcached/1.3.18/
